#######################################################
# Puppetmaster SERVER

class puppetmaster {
  tag("puppetmaster")
  notice(">>> puppetmaster server class <<<")

  include apache2
  include puppetmaster

  # Create this dir for autogenerated files - not in SVN
  file { "/etc/puppet/modules/users/files/authorized_keys/":
    ensure => directory,
    owner => 'root',
    group => 'root',
    mode  => '0755',
  }

  # Create this dir for autogenerated files - not in SVN
  file { "/etc/puppet/modules/users/manifests/auto/":
    ensure => directory,
    owner => 'root',
    group => 'root',
    mode  => '0755',
  }

  file { "/etc/default/puppetmaster":
    source => [
      "puppet:///modules/puppet/default_puppetmaster_$::fqdn",
      "puppet:///modules/puppet/default_puppetmaster",
    ],
    owner => 'root',
    group => 'root',
    mode  => '0644',
  }
  file { "/etc/cron.d/puppetmaster":
    source => [
      "puppet:///modules/puppet/cron_puppetmaster_$::fqdn",
      "puppet:///modules/puppet/cron_puppetmaster",
    ],
    owner => 'root',
    group => 'root',
    mode  => '0644',
  }

# TODO - disable and switch to passenger
#  service { "puppetmaster":
#    enable => true,
#    ensure => running,
#    hasstatus => true,
#    hasrestart => true,
#    require => File["/etc/default/puppetmaster"],
#  }

#  package { "puppetmaster":
#      ensure => $::lsbdistcodename ? {
#        "precise" => "2.7.11-1ubuntu2",
#        default   => "2.7.11-1puppetlabs1",
#      }
#  }
#  package { "puppetmaster-common":
#      ensure => $::lsbdistcodename ? {
#        "precise" => "2.7.11-1ubuntu2",
#        default   => "2.7.11-1puppetlabs1",
#      }
#  }

} # end class puppetmaster
