#!/usr/bin/perl

use warnings;
use strict;
use diagnostics;

my ($hostname, $port, $url, $httping, $interval, $count, $warn, $crit);
$httping="/usr/bin/httping";
($hostname, $port, $interval, $count, $url, $warn, $crit)=@ARGV;

open (my $HTTPING, "-|", "$httping -h $hostname -p $port -i $interval -c $count -G $url");

while (<$HTTPING>) {
        if ($_ =~ /^.*connects,.*?(\d{1,2}.\d\d)%/) {
                if ($1<$warn) {
                        print $_;
                        print "$1";
                        exit 0;
                } elsif ($1<$crit) {
                        print $_;
                        print "$1";
                        exit 1;
                } elsif ($1<100) {
                        print $_;
                        print "$1";
                        exit 2;
                } else {
                        print "This should never happen.\n";
                        exit 127;
                }
        }
}

close $HTTPING;
